export const FAKE_USERS = [
  {
    id: 1,
    username: "Guest User 1",
    profileImg: null,
    points: 0,
    assignedPoints: 0,
    roomKey: "rom1" /* room_id */,
  },
  {
    id: 2,
    username: "Guest User 2",
    profileImg: null,
    points: 0,
    assignedPoints: 0,
    roomKey: "rom1",
  },
  {
    id: 3,
    username: "Guest User 3",
    profileImg: null,
    points: 0,
    assignedPoints: 0,
    roomKey: "rom1",
  },
  {
    id: 4,
    username: "Room User 1",
    profileImg: null,
    points: 0,
    assignedPoints: 0,
    roomKey: null,
  },
  {
    id: 5,
    username: "Room User 2",
    profileImg: null,
    points: 0,
    assignedPoints: 0,
    roomKey: "rom2",
  },
];
